// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_gvI8BTeWMp54oc9E1AFzDNsZpaSECEo',
    appId: '1:932257944210:web:1edd1951aea814b5de4c4b',
    messagingSenderId: '932257944210',
    projectId: 'chatapp-bc5a5',
    authDomain: 'chatapp-bc5a5.firebaseapp.com',
    storageBucket: 'chatapp-bc5a5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyLm-46jwDqCbj6AtpphE3pkKjWYAzw94',
    appId: '1:932257944210:android:ac742c700738d240de4c4b',
    messagingSenderId: '932257944210',
    projectId: 'chatapp-bc5a5',
    storageBucket: 'chatapp-bc5a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8Uf4MR03gRApNJOp1GnjMHvrrrZvWaFA',
    appId: '1:932257944210:ios:f28cdaa11f16e374de4c4b',
    messagingSenderId: '932257944210',
    projectId: 'chatapp-bc5a5',
    storageBucket: 'chatapp-bc5a5.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );
}
